[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", optimism = "https://opt-mainnet.g.alchemy.com/v2/mFyWFWpLb_KJ54x3L4_DA7B5o5bzgu4h", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://binance.llamarpc.com", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", Avalanche = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon", celo = "https://rpc.ankr.com/celo" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
